version: 2
jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build Docker Image
          command: docker build . -f ./Dockerfile -t georgevella/azure-cli-helm:2.0.37-2.9.1
      - run:
          name: Push Docker Image
          command: docker push georgevella/azure-cli-helm:2.0.37-2.9.1